# Generated by Django 3.2.6 on 2021-08-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210811_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='features_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
