# Generated by Django 3.2.6 on 2021-08-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_features_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='features_image',
            new_name='featured_image',
        ),
    ]
